name: Bug Report
description: File a bug report
labels: ['Bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Give a brief explanation of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Describe how to reproduce this bug. Be sure to include screenshots or logs if they would help!
    validations:
      required: true
  - type: textarea
    id: explanation
    attributes:
      label: Additional Context
      description: |
        Not Required - Describe the bug in more detail. You could could include related issues, helpful 
        background knowledge, related documentation, or anything else that will help
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Where did you encounter the bug?
      multiple: true
      options:
        - clubs.utdnebula.com
        - dev.clubs.utdnebula.com
        - a local development branch (specify above)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser did you encounter this issue on?
      multiple: true
      options:
        - Firefox
        - Chromium
        - Safari
        - Not Applicable
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://about.utdnebula.com/docs/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
